---
title: "Task 1"
author: "Max Settineri"
date: "2023-02-15"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(tidyverse)
library(here)
library(broom)
library(patchwork)
library(GGally)
library(ggbeeswarm)

```

### Overview

This report....

Questions answered:

- 
- 

**Data source:** Abrahamson, W.G. 2019. Survival, growth and biomass estimates of two dominant palmetto species of south-central Florida from 1981 - 2017, ongoing at 5-year intervals ver 1. Environmental Data Initiative. https://doi.org/10.6073/pasta/f2f96ec76fbbd4b9db431c79a770c4d5

### Reading in and cleaning up the data

```{r}
palmetto <- read_csv(here('data', 'palmetto.csv')) %>% 
  select(height, length, width, green_lvs, species) %>% # selecting variables of interest
  drop_na() %>% # dropping NA values
  mutate(species_name = case_when(
    species == 1 ~ 'Serenoa repens', # new column for species name with full species names
    species == 2 ~ 'Sabal etonia'))
```

### Exploring differences between Serenoa repens and Sabal etonia

```{r, eval = FALSE}
# using GGally to look at trends and relationships between the two species and four variables of interest
palmetto %>% 
  select(species_name, height:green_lvs) %>% 
  ggpairs(aes(color = species_name))

# after initial analysis, looks to be: strong variation in green_lvs by species, slight variation in length and height, minimal difference in width
```

```{r}
plot_h <- ggplot(data = palmetto, aes(x = species_name, y = height)) +
  geom_beeswarm(aes(color = species_name)) +
  theme_minimal() +
  labs(x = "Species", y = "Height (cm)", subtitle = "Data from: Abrahamson, W.G. 2019") +
  guides(fill = guide_legend(title = "Species")) +
  geom_boxplot(fill = NA, width = 0.4, outlier.color = NA) +
  theme(axis.ticks.x = element_blank(),
    axis.text.x = element_blank()) +
  scale_color_manual(values = c("blue", "yellow")) +
  theme(legend.position = c(0.9, 0.8)) +
  theme(legend.background = element_rect(fill="white", 
                                  size=0, linetype="solid"))
  
plot_h
```

